import type { DashboardProductivityTabGroup } from "@/types/shared/productivity.types";

export const PREDEFINED_TAB_GROUP_TEMPLATES: DashboardProductivityTabGroup[] = [
  {
    _id: "preset-dev",
    userId: "local",
    name: "Dev",
    color: "#7C3AED",
    icon: "Code",
    isPredefined: true,
    sortOrder: 1,
    urls: [
      "https://claude.ai",
      "https://chatgpt.com",
      "https://gemini.google.com",
      "https://github.com",
      "https://stackoverflow.com",
    ],
    evolvedDomains: [],
    evolvedAt: null,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
  {
    _id: "preset-chill",
    userId: "local",
    name: "Chill",
    color: "#E11D48",
    icon: "Smile",
    isPredefined: true,
    sortOrder: 2,
    urls: [
      "https://youtube.com",
      "https://spotify.com",
      "https://reddit.com",
      "https://netflix.com",
    ],
    evolvedDomains: [],
    evolvedAt: null,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
  {
    _id: "preset-study",
    userId: "local",
    name: "Study",
    color: "#059669",
    icon: "BookOpen",
    isPredefined: true,
    sortOrder: 3,
    urls: [
      "https://wikipedia.org",
      "https://youtube.com",
      "https://udemy.com",
      "https://coursera.org",
    ],
    evolvedDomains: [],
    evolvedAt: null,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
  {
    _id: "preset-meeting",
    userId: "local",
    name: "Meeting",
    color: "#D97706",
    icon: "Video",
    isPredefined: true,
    sortOrder: 4,
    urls: [
      "https://teams.microsoft.com",
      "https://meet.google.com",
      "https://calendar.google.com",
      "https://notion.so",
    ],
    evolvedDomains: [],
    evolvedAt: null,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  },
];
